apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
  {{-  tpl (toYaml .Values.service.annotations) . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "trino.name" . }}
    release: {{ .Release.Name }}
    component: coordinator
